
export const NIGERIAN_COMMERCE_GLOSSARY = {
  "okrika": "Second-hand clothing, often imported",
  "akara": "Deep-fried bean cakes, a popular snack",
  "dash": "To give a tip or a small gift; sometimes used for a bribe",
  "garri": "Processed cassava flour, a staple food",
  "indomie": "Popular brand of instant noodles",
  "keke": "Tricycle used for public transportation",
  "danfo": "Yellow commercial buses in Lagos",
  "pure water": "Sachet water, 500ml",
  "suya": "Spiced grilled meat, usually beef or ram",
  "egusi": "Melon seed soup",
  "fufu": "Starchy dough made from cassava or yams",
  "jollof": "A popular rice dish",
  "moin moin": "Steamed bean pudding",
  "puff puff": "Deep-fried dough balls",
  "zobo": "Hibiscus tea drink",
  "kuli kuli": "Fried peanut snack",
  "kilishi": "Dried spiced meat, similar to jerky",
  "abacha": "African salad made from cassava",
  "bole": "Roasted plantain",
  "masa": "Rice cakes",
  "tuwo": "Starchy dough made from maize or rice",
  "amala": "Yam flour dough",
  "ewedu": "Jute leaf soup",
  "gbegiri": "Bean soup",
  "ogbono": "Wild mango seed soup",
  "pepper soup": "Spicy broth made with meat or fish",
  "naira": "Nigerian currency (NGN)",
  "kobo": "Sub-unit of the naira (100 kobo = 1 naira)",
  "k": "Slang for 1,000 (e.g., 5k = 5,000 NGN)",
  "box": "Slang for 100,000 NGN or a large sum of money",
  "m": "Slang for million (e.g., 2m = 2,000,000 NGN)",
  "put am for book": "To record a debt/credit sale",
  "collect on credit": "To buy something now and pay later",
  "pay balance": "To pay the remaining debt",
  "bring money": "To make a payment",
  "owe": "To be in debt",
  "customer": "Regular buyer or someone in a transaction",
  "oga": "Boss or senior person",
  "madam": "Female boss or senior person",
  "market": "Place of commerce or the goods being sold",
  "stock": "Goods available for sale",
  "wholesale": "Buying in bulk",
  "retail": "Selling in small quantities",
  "change": "Small denominations returned after a payment",
  "balance": "The amount remaining in a debt or the change given",
  "price": "Cost of an item",
  "discount": "Reduction in price",
  "last price": "The final, non-negotiable price",
  "bargain": "To negotiate the price",
  "hustle": "To work hard or the business itself",
  "gain": "Profit",
  "loss": "Loss in business",
  "credit": "Debt or the act of lending",
  "debt": "Money owed",
  "debtor": "Person who owes money",
  "creditor": "Person who is owed money",
  "receipt": "Proof of transaction",
  "invoice": "Bill for goods sold on credit",
  "waybill": "Document for goods being transported",
  "shop": "Place of business",
  "store": "Place for keeping goods",
  "warehouse": "Large storage for goods",
  "supplier": "Person or company that provides goods",
  "distributor": "Person or company that supplies retailers",
  "trader": "Person engaged in commerce",
  "merchant": "Wholesale trader",
  "hawker": "Street seller",
  "vendor": "Seller of goods or services",
  "customer care": "Service provided to customers",
  "market day": "Specific day for large-scale trading",
  "turnover": "Total sales in a period",
  "capital": "Money used to start or run a business",
  "investment": "Money put into a business for gain",
  "loan": "Borrowed money to be repaid with interest",
  "interest": "Cost of borrowing money",
  "collateral": "Security for a loan",
  "bank": "Financial institution",
  "transfer": "Moving money from one account to another",
  "pos": "Point of Sale machine for payments",
  "atm": "Automated Teller Machine",
  "cash": "Physical money",
  "cheque": "Written order for a bank to pay money",
  "online banking": "Banking via the internet",
  "mobile app": "Application for banking or business on a phone",
  "wallet": "Digital storage for money",
  "fintech": "Financial technology",
  "startup": "New business venture",
  "small business": "SME (Small and Medium Enterprise)",
  "informal sector": "Unregulated part of the economy",
  "tax": "Money paid to the government",
  "levy": "Local government charge",
  "permit": "Legal document to trade",
  "license": "Official permission to run a business",
  "registration": "Official listing of a business",
  "cac": "Corporate Affairs Commission (Nigeria)",
  "firs": "Federal Inland Revenue Service (Nigeria)",
  "vat": "Value Added Tax",
  "audit": "Official inspection of accounts",
  "bookkeeping": "Recording financial transactions",
  "accounting": "Managing financial records",
  "ledger": "Book or file for recording transactions",
  "balance sheet": "Summary of assets and liabilities",
  "p&l": "Profit and Loss statement",
  "cash flow": "Movement of money in and out of a business",
  "budget": "Financial plan for a period",
  "forecast": "Prediction of future financial performance",
  "inventory": "List of goods in stock",
  "reconciliation": "Comparing two sets of records for accuracy",
  "shortage": "Lack of goods or money",
  "surplus": "Excess of goods or money",
  "bad debt": "Debt that is unlikely to be repaid",
  "write-off": "Removing a bad debt from the books",
  "bankruptcy": "Legal state of being unable to pay debts",
  "liquidation": "Closing a business and selling its assets",
  "merger": "Combining two businesses",
  "acquisition": "One business buying another",
  "franchise": "Right to run a business under a brand name",
  "partnership": "Business owned by two or more people",
  "sole proprietorship": "Business owned by one person",
  "cooperative": "Business owned and run by its members",
  "association": "Group of traders or businesses",
  "union": "Group of workers or traders",
  "strike": "Refusal to work as a protest",
  "protest": "Public demonstration of disagreement",
  "inflation": "General increase in prices",
  "devaluation": "Reduction in the value of currency",
  "exchange rate": "Value of one currency against another",
  "black market": "Illegal or unofficial market",
  "subsidy": "Government support to keep prices low",
  "import": "Bringing goods from abroad",
  "export": "Sending goods abroad",
  "customs": "Government agency controlling imports/exports",
  "tariff": "Tax on imported goods",
  "quota": "Limit on the quantity of imported goods",
  "smuggling": "Illegal import or export of goods",
  "contraband": "Prohibited goods",
  "logistics": "Management of the flow of goods",
  "supply chain": "Process of producing and selling goods",
  "outsourcing": "Hiring another company to do work",
  "contract": "Legal agreement between parties",
  "agreement": "Mutual understanding between parties",
  "dispute": "Disagreement between parties",
  "settlement": "Resolution of a dispute",
  "arbitration": "Using a third party to resolve a dispute",
  "litigation": "Legal action in court",
  "lawyer": "Legal professional",
  "court": "Place for legal proceedings",
  "judge": "Official who presides over a court",
  "police": "Government agency for law enforcement",
  "efcc": "Economic and Financial Crimes Commission (Nigeria)",
  "icpc": "Independent Corrupt Practices Commission (Nigeria)",
  "scam": "Fraudulent scheme",
  "fraud": "Deception for financial gain",
  "corruption": "Dishonest or illegal behavior by officials",
  "bribery": "Giving or receiving tips for favors",
  "extortion": "Obtaining money by force or threats",
  "theft": "Stealing goods or money",
  "burglary": "Breaking into a place to steal",
  "robbery": "Stealing by force or threats",
  "security": "Protection of assets and people",
  "insurance": "Protection against financial loss",
  "premium": "Payment for insurance coverage",
  "claim": "Request for payment from an insurance company",
  "policy": "Insurance contract",
  "coverage": "Extracted risk in insurance",
  "risk": "Possibility of loss or damage",
  "hazard": "Source of danger",
  "accident": "Unintended event causing damage or injury",
  "emergency": "Serious situation requiring immediate action",
  "safety": "State of being protected from danger",
  "health": "State of being free from illness",
  "environment": "Surroundings in which a business operates",
  "sustainability": "Meeting needs without compromising the future",
  "ethics_work": "Moral principles governing behavior in work",
  "integrity": "Quality of being honest and having strong morals",
  "transparency": "Operating in an open and clear way",
  "accountability": "Responsibility for actions and decisions",
  "governance": "Way a business is directed and controlled",
  "compliance": "Following laws and regulations",
  "regulation": "Rule or directive made by an authority",
  "policy_business": "Plan or course of action in business",
  "strategy": "Plan of action to achieve a goal",
  "objective": "Goal to be achieved",
  "target": "Specific level to be reached",
  "kpi": "Key Performance Indicator",
  "benchmark": "Standard for comparison",
  "innovation": "New idea or method",
  "technology": "Application of scientific knowledge for business",
  "digitalization": "Using digital technologies to change business",
  "automation": "Using machines to do work",
  "ai": "Artificial Intelligence",
  "machine learning": "Subset of AI for pattern recognition",
  "big data": "Large sets of data for analysis",
  "cloud computing": "Using remote servers for data storage",
  "cybersecurity": "Protection of digital systems and data",
  "privacy": "Protection of personal information",
  "data protection": "Legal framework for managing data",
  "gdpr": "General Data Protection Regulation (EU)",
  "ndpr": "Nigeria Data Protection Regulation",
  "intellectual property": "Creations of the mind like inventions",
  "patent": "Legal right to an invention",
  "trademark": "Symbol or name representing a brand",
  "copyright": "Legal right to creative work",
  "brand": "Name or symbol identifying a business",
  "marketing": "Promoting and selling goods",
  "advertising": "Paid promotion of goods",
  "sales": "Act of selling goods",
  "customer service": "Assistance provided to customers",
  "feedback": "Information from customers about goods/services",
  "satisfaction": "State of being happy with a purchase",
  "loyalty": "Continued support for a brand",
  "retention": "Keeping customers over time",
  "acquisition_customer": "Getting new customers",
  "referral": "Recommendation from a customer",
  "promotion_marketing": "Activity to increase sales",
  "campaign": "Organized effort for marketing",
  "branding": "Creating a unique identity for a business",
  "positioning": "How a brand is perceived in the market",
  "segmentation": "Dividing the market into groups",
  "targeting": "Focusing on a specific market segment",
  "differentiation": "Making a brand stand out from competitors",
  "value proposition": "Reason why a customer should buy a brand",
  "competitive advantage": "Edge over competitors",
  "market share": "Portion of the market controlled by a brand",
  "market research": "Gathering information about the market",
  "survey": "Gathering data from a group of people",
  "focus group": "Small group for market research",
  "interview": "One-on-one conversation for research",
  "observation": "Watching customers in a natural setting",
  "analysis": "Detailed examination of data",
  "report": "Document summarizing research findings",
  "presentation": "Visual display of information",
  "meeting": "Gathering of people for discussion",
  "collaboration": "Working together on a project",
  "communication": "Exchanging information",
  "leadership": "Guiding and motivating a group",
  "management": "Organizing and controlling a business",
  "teamwork": "Cooperative effort of a group",
  "culture": "Shared values and behaviors in a business",
  "diversity": "Inclusion of different people in a business",
  "inclusion": "Ensuring everyone feels valued",
  "equality": "Fair treatment for everyone",
  "equity": "Fairness based on individual needs",
  "ethics_business": "Moral principles in business",
  "values": "Core beliefs of a business",
  "mission": "Purpose of a business",
  "vision": "Long-term goal of a business",
  "purpose": "Reason why a business exists",
  "impact": "Effect of a business on society",
  "social responsibility": "Business effort to benefit society",
  "philanthropy": "Giving money to charitable causes",
  "volunteering": "Giving time to charitable causes",
  "community": "Group of people living in the same area",
  "society": "People living together in an organized way",
  "economy": "System of production and consumption",
  "market_place": "Place where goods are bought and sold",
  "industry": "Group of businesses producing similar goods",
  "sector": "Part of the economy like agriculture",
  "region": "Specific geographic area",
  "country": "Nation or state",
  "global": "Relating to the whole world",
  "international": "Relating to more than one country",
  "trade_exchange": "Exchanging goods and services",
  "commerce_trade": "Large-scale trading",
  "business_org": "Organization engaged in commerce",
  "enterprise_business": "Business or company",
  "corporation_business": "Large business or company",
  "conglomerate_business": "Group of different businesses owned by one company",
  "multinational_business": "Business operating in many countries",
  "sme_business": "Small and Medium Enterprise",
  "startup_business": "New business venture",
  "entrepreneur_person": "Person who starts a business",
  "founder_person": "Person who establishes a business",
  "ceo_person": "Chief Executive Officer",
  "cfo_person": "Chief Financial Officer",
  "coo_person": "Chief Operating Officer",
  "cto_person": "Chief Technology Officer",
  "manager_person": "Person in charge of a group or department",
  "employee_person": "Person working for a business",
  "worker_person": "Person doing physical or mental work",
  "staff_person": "Group of people working for a business",
  "talent_person": "Skilled people in a business",
  "human_resources_dept": "Department managing employees",
  "recruitment_process": "Process of hiring new employees",
  "onboarding_process": "Process of integrating new employees",
  "training_process": "Process of teaching new skills",
  "development_process": "Process of improving existing skills",
  "performance_eval": "How well an employee does their work",
  "appraisal_eval": "Official evaluation of performance",
  "feedback_eval": "Information given to employees about performance",
  "coaching_eval": "Guiding and supporting employees",
  "mentoring_eval": "Advising and supporting employees",
  "promotion_eval": "Moving an employee to a higher position",
  "transfer_eval": "Moving an employee to a different department",
  "resignation_eval": "Act of leaving a job",
  "termination_eval": "Act of ending an employee's job",
  "retirement_eval": "Act of stopping work due to age",
  "salary_pay": "Fixed payment for work",
  "wage_pay": "Payment based on hours worked",
  "bonus_pay": "Extra payment for good work",
  "commission_pay": "Payment based on sales made",
  "benefits_pay": "Extra perks given to employees",
  "pension_pay": "Payment after retirement",
  "insurance_pay": "Health or life coverage for employees",
  "perks_pay": "Small benefits given to employees",
  "workplace_place": "Place where work is done",
  "office_place": "Place for administrative work",
  "factory_place": "Place for manufacturing goods",
  "remote_work_place": "Working from home or another location",
  "hybrid_work_place": "Mixing office and remote work",
  "flexibility_work": "Ability to change work arrangements",
  "well_being_work": "State of being happy and healthy at work",
  "engagement_work": "Level of commitment to work",
  "productivity_work": "Amount of work done in a period",
  "efficiency_work": "Doing work with minimum waste",
  "quality_work": "Standard of excellence in work",
  "innovation_work": "New ideas or methods in work",
  "creativity_work": "Ability to produce original ideas",
  "problem_solving_work": "Finding solutions to challenges",
  "decision_making_work": "Choosing a course of action",
  "critical_thinking_work": "Objective analysis of a situation",
  "collaboration_work": "Working with others on a task",
  "communication_work": "Clear exchange of information",
  "adaptability_work": "Ability to change with situations",
  "resilience_work": "Ability to recover from setbacks",
  "emotional_intelligence_work": "Ability to manage emotions",
  "ethics_work_work": "Moral principles in work",
  "integrity_work": "Honesty and strong morals in work",
  "accountability_work": "Responsibility for work results",
  "professionalism_work": "Conduct and behavior at work",
  "growth_business": "Increase in size or value of a business",
  "profitability_business": "Ability of a business to make profit",
  "expansion_business": "Increasing the scope of a business",
  "diversification_business": "Adding new goods or services",
  "market_entry_business": "Entering a new market",
  "internationalization_business": "Expanding business globally",
  "digital_transformation_business": "Using technology to change business",
  "customer_centricity_business": "Focusing on customer needs",
  "operational_excellence_business": "Improving internal processes",
  "strategic_alignment_business": "Ensuring business units work toward goals",
  "risk_management_business": "Identifying and mitigating risks",
  "financial_management_business": "Planning and controlling finances",
  "marketing_management_business": "Planning and executing marketing",
  "sales_management_business": "Directing the sales team",
  "operations_management_business": "Managing production and delivery",
  "supply_chain_management_business": "Managing the flow of goods",
  "human_resource_management_business": "Managing employees",
  "it_management_business": "Managing digital systems",
  "project_management_business": "Managing projects",
  "change_management_business": "Guiding business through changes",
  "quality_management_business": "Ensuring excellence in goods/services",
  "customer_relationship_management_business": "Managing customer interactions",
  "brand_management_business": "Building and protecting a brand",
  "innovation_management_business": "Fostering new ideas in business",
  "sustainability_management_business": "Ensuring business is sustainable",
  "ethics_management_business": "Ensuring business is ethical",
  "compliance_management_business": "Ensuring business follows laws",
  "security_management_business": "Protecting business assets",
  "crisis_management_business": "Handling serious business situations",
  "knowledge_management_business": "Sharing and using information",
  "data_management_business": "Managing and protecting data",
  "performance_management_business": "Improving business results",
  "strategic_management_business": "Long-term planning for success"
};
